#! /bin/bash

lockwall="$HOME/usr/pics/session/lock.png"
if ! [ -z "$1" ]; then
    # Gen wallpaper
    filetmp=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
    fileresize=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
    dual=$(xrandr | grep " connected" | grep "DP2")
    base="$HOME/.colorize/current/wallpaper-meowified.png"

    convert "$base" "$HOME/.colorize/current/lock.png" -gravity center -composite -matte "$filetmp"
    convert "$filetmp" -resize 1366x768 "$fileresize"

    if [ -z "$dual" ]; then
	   final="$fileresize"
    else
	   filemerge=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
	   montage -mode concatenate -tile x1 -gravity south "$filetmp" "$fileresize" "$filemerge"
	   final="$filemerge"
    fi
    cp "$final" "$lockwall"
    rm "$filetmp" "$fileresize" "$filemerge"
else
    # Lock
    #feh "$lockwall"
    i3lock -c 000000 -f -u -i "$lockwall"
fi